class calculadora:
  def __init__(self):
    print("Atributos")
    print("color")
    print("Modelo")
    print("tipo")
    print("Marca")
    print("pantalla")
    print("teclas")
    print("tamaño")
    print("fuente de energia")
    print("precio")
  def metodos(self):
    print("MEtodos")
    print("Calcular")
    print("sumar")
    print("Restar")
    print("Dividir")
    print("Prender")
objeto_calculadora=calculadora()
objeto_calculadora.metodos()