class avion:
  def __init__(self):
    print("Atributos")
    print("color")
    print("Modelo")
    print("Aerolineaa")
    print("Marca")
    print("motores")
    print("asientos")
    print("baños")
    print("combustible")
    print("precio")
  def metodos(self):
    print("MEtodos")
    print("Volar")
    print("Transportar")
    print("cargar")
    print("Prender")
    print("Frenar")
objeto_avion=avion()
objeto_avion.metodos()