class coche:
  def __init__(self):
    print("Atributos")
    print("color")
    print("Modelo")
    print("estandar")
    print("Marca")
    print("automatico")
    print("asientos")
    print("tipo de motor")
    print("combustible")
    print("precio")
  def metodos(self):
    print("MEtodos")
    print("Manejar")
    print("Transportar")
    print("cargar")
    print("Prender")
    print("Frenar")
objeto_coche=coche()
objeto_coche.metodos()