class futbolista:
  def __init__(self):
    print("equipo")
    print("posicion")
    print("numero")
    print("altura")
    print("peso")
    print("posicion")
    print("condicion fisica")
    print("rapides")
    print("salario")
    print("Abilidad")
  def metodos(self):
    print("MEtodos")
    print("brincar")
    print("Saltar")
    print("correr")
    print("atacar")
    print("ganar")
objeto_futbolista=futbolista()
objeto_futbolista.metodos()